name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'src/'
      - '.github/workflows/build.yml'
      - 'package*.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        nodejs:
          - 19
          - 20
          - 21
          - 22
          - 23
          - 24

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '${{ matrix.nodejs }}'

      - name: Install dependencies
        run: npm ci

      - name: Build HTML + CSS
        run: npm run build
