name: ESLint HTML

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/lint-html.yml'
      - 'src/config/eslint.html.config.ts'
      - 'src/content.html'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/lint-html.yml'
      - 'src/config/eslint.html.config.ts'
      - 'src/content.html'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun ci

      - name: Lint scripts
        run: bun lint:scripts
